version: '3.5'
networks:
  changedetection:
    name: changedetection
    driver: bridge
 
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    environment:
      - PORT= 5002
      - PUID= 1000
      - PGID= 1000
      - PLAYWRIGHT_DRIVER_URL=ws://172.31.27.52:3000/?stealth=1&--disable-web-security=true
    ports:
      - 5002:5002
    restart: unless-stopped
    depends_on:
      playwright-chrome:
          condition: service_started
    networks:
      - changedetection
 
  playwright-chrome:
    hostname: playwright-chrome
    container_name: playwright-chrome
    image: browserless/chrome:latest
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=10
      - CHROME_REFRESH_TIME= 600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_STEALTH=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
    networks:
      - changedetection
 
volumes:
  changedetection-data:
